---
title: "Week 10_2"
author: "Janine Par"
date: '2022-05-20'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(plyr)
library(ggplot2)
library (lm.beta)
library (car)
library(dplyr)
library(caTools)
```


```{r binaryclassifierdata }

#Fit a Logistic Regression Model

## Set the working directory to the root of your DSC 520 directory
setwd("C:/Users/janin/OneDrive/Documents/R_repo/dsc520/")

## Load the `data/binaryclassifierdata`
binaryclass_df <- read.csv("data/binary-classifier-data.csv", header=TRUE, comment.char = "@")

str(binaryclass_df)

head (binaryclass_df)

```

```{r logisticRegression}
#Fit a logistic regression model to the binary-classifier-data.csv dataset
# The dataset (found in binary-classifier-data.csv) contains three variables; label, x, and y. The label variable is either 0 or 1 and is the output we want to predict using the x and y variables.

binaryclass.model <- glm(label~x+y, data=binaryclass_df, family=binomial())

summary (binaryclass.model)
```

```{r accuracy, results='hide'}

#What is the accuracy of the logistic regression classifier?
  
#Split data
bcsplit <- sample.split(binaryclass_df, SplitRatio = 0.8)

bcsplit_train <- subset(binaryclass_df,tssplit='True')
bcsplit_train

bcsplit_test <- subset(binaryclass_df,tssplit='Fales')
bcsplit_test

#Predict 
res.train <- predict(binaryclass.model,bcsplit_train,type ="response")
res.train 

res.test <- predict(binaryclass.model,bcsplit_test,type ="response")
res.test 

```

```{r confusion matrix}
confmatrix <- table(Actual_value=bcsplit_train$label, Predicted_Value= res.train > 0.5)

(confmatrix [[1,1]] + confmatrix [[2,2]])/sum(confmatrix)
```

**Accuracy of the model is 58.3%**
